version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - Kqzz
  ignore:
  - dependency-name: serverless
    versions:
    - 2.33.1
    - 2.36.0
    - 2.37.2
